### PR TITLE
Clean up NavBar entities

### PR DESCRIPTION
**Pull request by bobbybleu**

### CODE REVIEW

**Review by JohnWebster1 — COMMENTED** [review]
Make sure that you are able to include the .gitignore in the pull request. This is too long for a change and will be problematic.

**Review by domfernando319 — APPROVED** [review]
Looks okay.

**Comment by nhulston** [comment]
There are conflicting files changed. I don't think this should be merged as it may undo previous merged PRs.
I recommend switching to master branch, updating the branch, and then redoing your changes before making another PR to avoid any conflicts.

**Review by nhulston — CHANGES_REQUESTED** [review]
There are conflicting files changed. I don't think this should be merged as it may undo previous merged PRs.
I recommend switching to master branch, updating the branch, and then redoing your changes before making another PR to avoid any conflicts.

**Pull request closed without merging**
