### PR TITLE
Cleanup footer, fix resizing issues

### PR DESCRIPTION
**Pull request by nhulston**
Footer changes
- I just made the footer it's own component. That way, when we add footers to new pages, we don't have to copy and paste code over.
- I also removed all the copy/pasting of code. For example, the styling for each h2 and p was copy and pasted over and over again. Instead, I made a styled-component so that the CSS only needs to be changed once when updating in the future

Resizing issue fixed
- the sidebar and page content needs to be wrapped in div (flex, row) so that when resizing the screen width, the height of the sidebar and page content are all the same. This ensures that any content overflow won't go into the footer

### CODE REVIEW

**Comment by bobbybleu** [comment]
great issue clean up could use more meaningful comments

**Comment by JohnWebster1** [comment]
Good cleanup of page resize. Maybe handle the footer horizontal text.

**Comment by domfernando319** [comment]
Nice job cleaning up the footer element. The file is now more readable.

**Comment by nhulston** [comment]
> great issue clean up could use more meaningful comments

Thanks, just added more descriptive comments.

**Pull request merged**
